# Generated by Django 4.0.1 on 2024-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='lastExamination',
            field=models.DateField(blank=True, null=True),
        ),
    ]
