# Generated by Django 4.0.1 on 2024-06-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_patient_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselling',
            old_name='aggression',
            new_name='agression',
        ),
    ]
