# Generated by Django 4.0.1 on 2024-06-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_rename_aggression_counselling_agression'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselling',
            old_name='agression',
            new_name='aggression',
        ),
    ]
